name: myapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  go_router: ^17.0.0
  firebase_core: ^4.2.1
  firebase_vertexai: ^2.2.0
  firebase_auth: ^6.1.2
  image_picker: ^1.1.2
  http: ^1.2.2
  percent_indicator: ^4.2.3
  cloud_firestore: ^6.1.0
  firebase_storage: ^13.0.4
  uuid: ^4.4.2
  intl: ^0.19.0
  firebase_database: ^12.1.0
  shared_preferences: ^2.1.0
  provider: ^6.0.5

  # Thư viện Zego Call
  zego_uikit_prebuilt_call: ^4.22.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  
  # ĐÃ XÓA: firebase_auth_mocks để tránh xung đột
  # Nếu sau này bạn cần viết Unit Test, hãy cấu hình dependency_overrides sau.

flutter:
  uses-material-design: true

  assets:
    - assets/images/default_avatar.png