name: myapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.3
  go_router: ^17.0.0
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  image_picker: ^1.2.1
  http: ^1.6.0
  percent_indicator: ^4.2.5
  cloud_firestore: ^6.1.0
  firebase_storage: ^13.0.4
  uuid: ^4.5.2
  intl: ^0.20.2
  firebase_database: ^12.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/default_avatar.png
